config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    url(r'^$', 'fifo.landing.views.home', name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, include(admin.site.urls)),

    # all auth
    url(r'^accounts/', include('allauth.urls')),

    # users
    url(r'^users/', include('fifo.users.urls', namespace='users')),

    # api
    url(r'^api/v1/', include('fifo.api_v1.api', namespace='api_v1')),

    # queues
    url(r'^queues/', include("fifo.queues.urls", namespace="queues")),
    
    # entries
    #url(r'^entries/', include("fifo.entries.urls", namespace="entries")),
    
    

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]


admin.site.site_header = 'fifo.li admin site'
admin.site.site_title = 'fifo.li staff '

fifo/entries/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the UserListView
    # url(
    #     regex=r'^$',
    #     view=views.UserListView.as_view(),
    #     name='list'
    # ),


]

fifo/queues/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
       url(
        regex=r'^all/$',
        view=views.all_queues,
        name='all_queues'
    ),
    url(
        regex=r'^active/$',
        view=views.active_queues,
        name='active_queues'
    ),
    url(
        regex=r'^(?P<id>[^/]+)/$',
        view=views.queue_detail,
        name='queue_detail'
    ),
    url(
        regex=r'^manage/(?P<id>[^/]+)/$',
        view=views.manage_queue,
        name='manage_queue'
    ),
 
]

fifo/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),

    # URL pattern for the UserRedirectView
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),

    # URL pattern for the UserDetailView
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    # URL pattern for the UserUpdateView
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

fifo/entries/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _
from django.conf import settings

from ..queues.models import Queue

import uuid

@python_2_unicode_compatible
class Entry(models.Model):
    
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, related_name='entries')
    queue = models.ForeignKey(Queue, null=False, related_name='entries')
    created = models.DateTimeField(auto_now_add=True)
    
    start = models.DateTimeField(_('start date'), blank=True, null=True)
    finish = models.DateTimeField(_('finish date'), blank=True, null=True)
    
    
    resolved = models.BooleanField(_('resolved'), default=False, blank=False)
    active = models.BooleanField(_('active'), default=True, blank=False)

    #description = models.TextField(_('entry description'), max_length=512, blank=True)

    def __str__(self):
        return self.owner.name + " Entry"

    def get_absolute_url(self):
        return reverse('entries:detail', kwargs={'id': self.id})

    
    
    
    

fifo/landing/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

fifo/queues/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _
from django.conf import settings

import uuid


@python_2_unicode_compatible
class Queue(models.Model):
    
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, related_name='queues')
    
    name = models.CharField(_('name'), max_length=64, blank=False)

    created = models.DateTimeField(auto_now_add=True)
    
    
    active = models.BooleanField(_('active'), default=False, blank=False)
    
    description = models.TextField(_('queue description'), max_length=512, blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('queues:detail', kwargs={'id': self.id})

    
    
    
    
    
    
    
    
    
    
    

fifo/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _

import uuid


@python_2_unicode_compatible
class User(AbstractUser):
    
    
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    org_id = models.IntegerField(_('Organization ID'), default=-1, blank=False)
    name = models.CharField(_('Name of User'), blank=False, max_length=255)
    
    phone = models.CharField(_('Phone Number'), max_length=10, blank=True)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

fifo/users/forms.py
from django import forms


class SignupForm(forms.Form):
    """
    Custom Signup Form for Django AllAuth
    AllAuth settings key points to this.
    """
    first_name = forms.CharField(max_length=32, label='First Name')
    last_name = forms.CharField(max_length=32, label='Last Name')
    org_id = forms.IntegerField(label='ID')
    phone = forms.CharField(label='Phone Number')

    
    
    def signup(self, request, user):
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.org_id = self.cleaned_data['org_id']
        user.phone = self.cleaned_data['phone']
        user.name = user.first_name + ' ' + user.last_name
        user.save()

fifo/entries/views.py
from django.shortcuts import render

# Create your views here.

fifo/landing/views.py
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required

from ..queues.models import Queue
from ..entries.models import Entry

def home(request):
    context = {}
    
    
    active_queues = Queue.objects.filter(active=True)
    
    all_entries = []
    
    for queue in active_queues:
        entries = Entry.objects.filter(queue=queue, active=True)
        all_entries.append(entries)
        
    
    
    context['active_queues'] = zip(active_queues, all_entries)
    
    return render(request, 'landing/home.html', context)

fifo/queues/views.py
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required

from .models import Queue
from ..entries.models import Entry

@login_required
def active_queues(request):
    context = {}
    
    return render(request, 'queues/active_queues.html', context)

@login_required
def all_queues(request):
    context = {}
    queues = Queue.objects.filter(owner=request.user.id)
    context['queues'] = queues
    
    return render(request, 'queues/all_queues.html', context)

@login_required
def queue_detail(request, id):
    context = {}
    
    return render(request, 'queues/queue_detail.html', context)

@login_required
def manage_queue(request, id):
    context = {}
    
    queue = Queue.objects.get(id=id)
    entries = Entry.objects.filter(queue=queue, active=True)
    
    context['queue'] = queue
    context['entries'] = entries
   
    
    return render(request, 'queues/manage_queue.html', context)

fifo/users/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'

fifo/templates/base/all_auth_base.html
{% load staticfiles i18n %}
<!DOCTYPE html>
<!--[if IE 9 ]><html class="ie9"><![endif]-->
    <head>
    {% block head %}{% include 'base/head.html' %}{% endblock %}
    {% block extra_head %}{% endblock %}

    <title>{% block title %} fifo.li {% endblock %}</title>
    {% block css %}

    <link href="{% static 'vendors/bower_components/animate.css/animate.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendors/bower_components/material-design-iconic-font/dist/css/material-design-iconic-font.min.css' %}" rel="stylesheet">

    <!-- CSS -->
    <link href="{% static 'css/app.min.1.css' %}" rel="stylesheet">
    <link href="{% static 'css/app.min.2.css' %}" rel="stylesheet">

    {% endblock %}
    {% block extra_css %}{% endblock %}

    {#    {% block angular %}#}
    {#    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.4/angular.min.js"></script>#}
    {#    {% endblock %}#}

    </head>
    <body class="login-content">

        {% if messages %}
        {% for message in messages %}
            <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
        {% endfor %}
        {% endif %}


        {% block content %}



        {% endblock content %}

        {% block modal %}{% endblock modal %}




        {% block loader %} {% include 'base/loader.html' %} {% endblock %}


        {% include 'base/oldIEWarning.html' %}

        {% block scripts %}

        <script src="{% static 'vendors/bower_components/jquery/dist/jquery.min.js' %}"></script>
        <script src="{% static 'vendors/bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>

        <script src="{% static 'vendors/bower_components/Waves/dist/waves.min.js' %}"></script>

        <!-- Placeholder for IE9 -->
        <!--[if IE 9 ]>
            <script src="{% static 'vendors/bower_components/jquery-placeholder/jquery.placeholder.min.js' %}"></script>
        <![endif]-->

        <script src="{% static 'js/functions.js' %}"></script>


        {% endblock %}
        {% block extra_scripts %}{% endblock %}

    </body>
  </html>

fifo/templates/base/base.html
{% load staticfiles i18n %}
<!DOCTYPE html>
<!--[if IE 9 ]><html class="ie9"><![endif]-->
    <head>
    {% block head %}{% include 'base/head.html' %}{% endblock %}
    {% block extra_head %}{% endblock %}

    <title>{% block title %} fifo.li {% endblock %}</title>
    
    <!-- CSS -->
    
    {% block css %}{% include 'base/css.html' %}{% endblock %}
    {% block extra_css %}{% endblock %}

    {#    {% block angular %}#}
    {#    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.4/angular.min.js"></script>#}
    {#    {% endblock %}#}

    {% block core_css %}{% include 'base/core_css.html' %}{% endblock %}

    </head>
    <body>

        {% block header %} {% include 'base/header.html' %} {% endblock %}


        <section id="main">

            {% block sidebar %} {% include 'base/sidebar.html' %} {% endblock %}
            {# {% block chat %} {% include 'base/chat.html' %} {% endblock %}#}

            <section id="content">
                <div class="container">

                    {% block page_header %}
                    <div class="block-header">
                        <h2>{% block page_header_title %}  {% endblock %}</h2>

                    {% endblock %}
                    {% if messages %}
                    {% for message in messages %}
                        <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
                    {% endfor %}
                    {% endif %}

{#                        <ul class="actions">#}
{##}
{#                            <li class="dropdown">#}
{#                                <a href="" data-toggle="dropdown">#}
{#                                    <i class="zmdi zmdi-more-vert"></i>#}
{#                                </a>#}
{##}
{#                                <ul class="dropdown-menu dropdown-menu-right">#}
{#                                    <li>#}
{#                                        <a href="">Refresh</a>#}
{#                                    </li>#}
{#                                </ul>#}
{#                            </li>#}
{#                        </ul>#}

                    </div>
                    
                    
                 


                  {% block content %}
                    <p>Content</p>
                  {% endblock content %}

                </div>
            </section>
        </section>

        {% block modal %}{% endblock modal %}


        {% block footer %} {% include 'base/footer.html' %} {% endblock %}


        {% block loader %} {% include 'base/loader.html' %} {% endblock %}


        {% include 'base/oldIEWarning.html' %}


        {% block scripts %} {% include 'base/scripts.html' %} {% endblock %}
        
        

        
        
        {% block extra_scripts %}{% endblock %}
        {% block core_scripts %} {% include 'base/core_scripts.html' %} {% endblock %}

    </body>
  </html>

fifo/templates/base/chat.html
{% load staticfiles i18n %}
            <aside id="chat" class="sidebar c-overflow">

                <div class="chat-search">
                    <div class="fg-line">
                        <input type="text" class="form-control" placeholder="Search People">
                    </div>
                </div>

                <div class="listview">
                    <a class="lv-item" href="">
                        <div class="media">
                            <div class="pull-left p-relative">
                                <img class="lv-img-sm" src="{% static 'img/profile-pics/2.jpg' %}" alt="">
                                <i class="chat-status-busy"></i>
                            </div>
                            <div class="media-body">
                                <div class="lv-title">Bilal</div>
                                <small class="lv-small">Available</small>
                            </div>
                        </div>
                    </a>

                    <a class="lv-item" href="">
                        <div class="media">
                            <div class="pull-left">
                                <img class="lv-img-sm" src="{% static 'img/profile-pics/1.jpg' %}" alt="">
                            </div>
                            <div class="media-body">
                                <div class="lv-title">CP</div>
                                <small class="lv-small">Last seen 3 hours ago</small>
                            </div>
                        </div>
                    </a>

                    <a class="lv-item" href="">
                        <div class="media">
                            <div class="pull-left p-relative">
                                <img class="lv-img-sm" src="{% static 'img/profile-pics/3.jpg' %}" alt="">
                                <i class="chat-status-online"></i>
                            </div>
                            <div class="media-body">
                                <div class="lv-title">Bruce</div>
                                <small class="lv-small">Availble</small>
                            </div>
                        </div>
                    </a>

                    <a class="lv-item" href="">
                        <div class="media">
                            <div class="pull-left p-relative">
                                <img class="lv-img-sm" src="{% static 'img/profile-pics/4.jpg' %}" alt="">
                                <i class="chat-status-online"></i>
                            </div>
                            <div class="media-body">
                                <div class="lv-title">Ryan</div>
                                <small class="lv-small">Availble</small>
                            </div>
                        </div>
                    </a>

                    <a class="lv-item" href="">
                        <div class="media">
                            <div class="pull-left">
                                <img class="lv-img-sm" src="{% static 'img/profile-pics/5.jpg' %}" alt="">
                            </div>
                            <div class="media-body">
                                <div class="lv-title">Yoshi</div>
                                <small class="lv-small">Last seen 3 days ago</small>
                            </div>
                        </div>
                    </a>

                    <a class="lv-item" href="">
                        <div class="media">
                            <div class="pull-left">
                                <img class="lv-img-sm" src="{% static 'img/profile-pics/6.jpg' %}" alt="">
                            </div>
                            <div class="media-body">
                                <div class="lv-title">Dale</div>
                                <small class="lv-small">Last seen 2 minutes ago</small>
                            </div>
                        </div>
                    </a>
                    <a class="lv-item" href="">
                        <div class="media">
                            <div class="pull-left p-relative">
                                <img class="lv-img-sm" src="{% static 'img/profile-pics/7.jpg' %}" alt="">
                                <i class="chat-status-busy"></i>
                            </div>
                            <div class="media-body">
                                <div class="lv-title">Torie</div>
                                <small class="lv-small">Busy</small>
                            </div>
                        </div>
                    </a>
                    <a class="lv-item" href="">
                        <div class="media">
                            <div class="pull-left p-relative">
                                <img class="lv-img-sm" src="{% static 'img/profile-pics/4.jpg' %}" alt="">
                                <i class="chat-status-busy"></i>
                            </div>
                            <div class="media-body">
                                <div class="lv-title">Stephanie</div>
                                <small class="lv-small">Busy</small>
                            </div>
                        </div>
                    </a>
                </div>
            </aside>

fifo/templates/base/core_css.html
{% load staticfiles i18n %}

        <link href="{% static 'css/app.min.1.css' %}" rel="stylesheet">
        <link href="{% static 'css/app.min.2.css' %}" rel="stylesheet">

fifo/templates/base/core_scripts.html
{% load staticfiles i18n %}
        <script src="{% static 'js/functions.js' %}"></script>
        <script src="{% static 'js/demo.js' %}"></script>

fifo/templates/base/css.html
{% load staticfiles i18n %}

        <!-- Vendor CSS -->
        <link href="{% static 'vendors/bower_components/animate.css/animate.min.css' %}" rel="stylesheet">
        <link href="{% static 'vendors/bower_components/bootstrap-sweetalert/lib/sweet-alert.css' %}" rel="stylesheet">
        <link href="{% static 'vendors/bower_components/material-design-iconic-font/dist/css/material-design-iconic-font.min.css' %}" rel="stylesheet">
        <link href="{% static 'vendors/bower_components/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.min.css' %}" rel="stylesheet">

fifo/templates/base/footer.html
        <footer id="footer">
            Copyright &copy; 2016 fifo.li
            
            <ul class="f-menu">
                <li><a href="mailto:cmajgaar@colby.edu?Subject=fifo.li">Contact</a></li>
            </ul>
        </footer>

fifo/templates/base/head.html
{% load staticfiles i18n %}
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="icon" href="{% static 'img/favicon.ico' %}">

fifo/templates/base/loader.html
        <!-- Page Loader -->
        <div class="page-loader">
            <div class="preloader pls-blue">
                <svg class="pl-circular" viewBox="25 25 50 50">
                    <circle class="plc-path" cx="50" cy="50" r="20" />
                </svg>

                <p>fifo.li</p>
            </div>
        </div>

fifo/templates/base/oldIEWarning.html
        <!-- Older IE warning message -->
        <!--[if lt IE 9]>
            <div class="ie-warning">
                <h1 class="c-white">Warning!!</h1>
                <p>You are using an outdated version of Internet Explorer, please upgrade <br/>to any of the following web browsers to access this website.</p>
                <div class="iew-container">
                    <ul class="iew-download">
                        <li>
                            <a href="http://www.google.com/chrome/">
                                <img src="img/browsers/chrome.png" alt="">
                                <div>Chrome</div>
                            </a>
                        </li>
                        <li>
                            <a href="https://www.mozilla.org/en-US/firefox/new/">
                                <img src="img/browsers/firefox.png" alt="">
                                <div>Firefox</div>
                            </a>
                        </li>
                        <li>
                            <a href="http://www.opera.com">
                                <img src="img/browsers/opera.png" alt="">
                                <div>Opera</div>
                            </a>
                        </li>
                        <li>
                            <a href="https://www.apple.com/safari/">
                                <img src="img/browsers/safari.png" alt="">
                                <div>Safari</div>
                            </a>
                        </li>
                        <li>
                            <a href="http://windows.microsoft.com/en-us/internet-explorer/download-ie">
                                <img src="img/browsers/ie.png" alt="">
                                <div>IE (New)</div>
                            </a>
                        </li>
                    </ul>
                </div>
                <p>Sorry for the inconvenience!</p>
            </div>   
        <![endif]-->

fifo/templates/base/scripts.html
{% load staticfiles i18n %}

        <!-- Javascript Libraries -->
        <script src="{% static 'vendors/bower_components/jquery/dist/jquery.min.js' %}"></script>
        <script src="{% static 'vendors/bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>

        <script src="{% static 'vendors/bower_components/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js' %}"></script>
        <script src="{% static 'vendors/bower_components/Waves/dist/waves.min.js' %}"></script>
        <script src="{% static 'vendors/bootstrap-growl/bootstrap-growl.min.js' %}"></script>
        <script src="{% static 'vendors/bower_components/bootstrap-sweetalert/lib/sweet-alert.min.js' %}"></script>

        <!-- Placeholder for IE9 -->
        <!--[if IE 9 ]>
            <script src="{% static 'vendors/bower_components/jquery-placeholder/jquery.placeholder.min.js' %}"></script>
        <![endif]-->

fifo/templates/base/sidebar.html
{% load staticfiles i18n %}

            <aside id="sidebar" class="sidebar c-overflow">
                <div class="profile-menu">
                    <a href="">
                        <div class="profile-pic">
                            <img src="{% static 'img/profile-pics/1.png' %}" alt="">
                        </div>

                        <div class="profile-info">
                             {% if request.user.is_authenticated %}
                                {{request.user.first_name}} {{request.user.last_name}}
                              {% else %}
                                  Colby User
                              {% endif %}
                            <i class="zmdi zmdi-caret-down"></i>
                        </div>
                    </a>

                    <ul class="main-menu">
                        
                        {% if request.user.is_authenticated %}
                        
                        <!--<li>-->
                        <!--    <a href="#"><i class="zmdi zmdi-account"></i> View Profile</a>-->
                        <!--</li>-->
                        <li>
                            <a href=""><i class="zmdi zmdi-settings"></i> Settings</a>
                        </li>
                        <li>
                            <a href="{% url 'account_logout' %}"><i class="zmdi zmdi-time-restore"></i> Logout</a>
                        </li>
                        
                        {% else %}
                        <li>
                            <a href="{% url 'account_login' %}"><i class="zmdi zmdi-account"></i>Login</a>
                        </li>
                        <li>
                            <a href="{% url 'account_signup' %}"><i class="zmdi zmdi-time-restore"></i> SignUp</a>
                        </li>
                        
                        
                        {% endif %}
                        
                    </ul>
                </div>


                <ul class="main-menu">
                    <li>
                        <a href="{% url 'home' %}"><i class="zmdi zmdi-view-dashboard"></i> <strong>Dashboard</strong></a>
                    </li>
                    
                     {% if request.user.is_authenticated %}

                    <li>
                        <a href="{% url 'queues:all_queues' %}"><i class="zmdi zmdi-view-home"></i> <strong>All Queues</strong></a>
                    </li>
                    <li>
                        <a href="{% url 'queues:active_queues' %}"><i class="zmdi zmdi-view-home"></i> <strong>Active Queues</strong></a>
                    </li>
                    {% endif %}
                    
                </ul>
            </aside>